version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.15
    steps:
      - checkout
      - run: php --version
      - run: curl -sS https://getcomposer.org/installer -o composer-setup.php
      - run: sudo php composer-setup.php --filename=composer --install-dir=/usr/local/bin --version=2.2
      - run: sudo rm composer-setup.php


workflows:
  build-workflow:
    jobs:
      - build
