version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/php:8.1.15
    steps:
      - checkout

      - run:
          name: Install composer
          command: |
            curl -sS  https://getcomposer.org/installer -o composer-setup.php
            sudo php composer-setup.php --filename=composer --install-dir=/usr/local/bin --2.2
            sudo rm composer-setup.php
            composer install

      - run:
          name: phpstan
          command:
            vendor/bin/phpstan analyse

      - run:
          name: phpcs
          command:
            vendor/bin/phpcs

      - run:
          name: Security checker
          command:
            vendor/bin/security-checker security:check

workflows:
  build-workflow:
    jobs:
      - lint
