version: 2.1

default: &default
  docker:
    - image: cimg/php:8.1.15

composer_install: &composer_install
  run:
    name: Install composer
    command: |
      curl -sS  https://getcomposer.org/installer -o composer-setup.php
      sudo php composer-setup.php --filename=composer --install-dir=/usr/local/bin --2.2
      sudo rm composer-setup.php
      composer install

ddev_install: &ddev_install
  run:
    name: DDEV composer
    command: |
      curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      rm install_ddev.sh

jobs:
  lint:
    <<: *default
    steps:
      - checkout
      - *composer_install

      - run:
          name: phpstan
          command:
            vendor/bin/phpstan analyse

      - run:
          name: phpcs
          command:
            vendor/bin/phpcs

      - run:
          name: Security checker
          command:
            vendor/bin/security-checker security:check
  test:
    machine:
      image: ubuntu-2004:current
    environment:
      DDEV_NONINTERACTIVE: "true"
    steps:
      - checkout

      - *ddev_install

      - run:
          name: PHPUnit
          command: |
            ddev start
            ddev phpunit --do-not-cache-result


workflows:
  build-workflow:
    jobs:
      - lint
      - test
